from __future__ import annotations

from pathlib import Path

from app_paths import app_dir


APP_NAME = "Local Granola"
SAMPLE_RATE = 16_000
CHUNK_FRAMES = 2_048
BLOCKSIZE = 2_048
DEFAULT_CHUNK_WINDOW_SECONDS = 60.0
OUTPUT_DIR = app_dir() / "output"
MODELS_DIR = app_dir() / "models"
WHISPER_DOWNLOAD_ROOT = MODELS_DIR
WHISPER_LOCAL_MODEL_DIR = MODELS_DIR / "whisper"
WHISPER_MODEL_CANDIDATES = ("tiny.en", "base.en", "small.en", "tiny")
WHISPER_MODEL_NAME = "tiny.en"
WHISPER_MODEL_REPO_DIR = MODELS_DIR / f"models--Systran--faster-whisper-{WHISPER_MODEL_NAME}"
WHISPER_LANGUAGE = "en"
WHISPER_DEVICE = "cpu"
WHISPER_COMPUTE_TYPE = "int8"
WHISPER_BEAM_SIZE = 3
WHISPER_BEST_OF = 3
WHISPER_INITIAL_PROMPT = ""
LIVE_TRANSCRIBE_POLL_SECONDS = 0.5
LIVE_TRANSCRIBE_OVERLAP_SECONDS = 1.5
LIVE_TRANSCRIBE_MIN_AUDIO_SECONDS = 1.0
LIVE_TRANSCRIBE_STEP_SECONDS = 0.5
LIVE_TRANSCRIBE_WINDOW_SECONDS = 4.0
LIVE_TRANSCRIBE_STABILIZATION_SECONDS = 1.25
LIVE_TRANSCRIBE_PREVIEW_LOOKBACK_SECONDS = 4.0
LIVE_TRANSCRIBE_BEAM_SIZE = 1
LIVE_TRANSCRIBE_BEST_OF = 1
LIVE_TRANSCRIBE_VAD_FILTER = True
LIVE_TRANSCRIBE_ACCEPT_OVERLAP_SECONDS = 0.35
TRANSCRIPTION_MIX_WINDOW_SECONDS = 0.25
TRANSCRIPTION_MIX_SILENCE_RMS = 0.008
TRANSCRIPTION_MIX_DOMINANCE_RATIO = 1.2
